server {
    listen 80 default_server;
    listen [::]:80 default_server;

    access_log off;
    log_not_found off;
    error_log  /dev/stderr error;

    # Serve MISP directly over HTTP — no HTTPS redirect for local dev
    include includes/misp;
}
