"""Layer 4 — MISP exporter.

Creates a MISP event from a verdict document containing ONLY technical IoCs
(sender IP, URLs, attachment SHA-256s, sending domain).  Email body content,
subject line, and recipient addresses are NEVER included (FR-L4-09, SEC-12).

Threat level is set based on the blocking layer per FR-L4-11:
  Layer 1 hit          → High  (threat_level_id = 1)
  Layer 2 Tier 1 hit   → High
  Layer 2 Tier 2/3 hit → Medium (id = 2)
  Layer 3 hit          → High

Exports on both "phishing" and "suspicious" verdicts.
Retries up to 3 times with exponential backoff on transient failures (FR-L4-13).
"""
import asyncio
from datetime import UTC, datetime

import structlog

logger = structlog.get_logger()

_MAX_RETRIES = 3
_RETRY_BACKOFF_BASE = 2  # seconds


def _threat_level_id(verdict_doc: dict) -> str:
    """Map blocking layer to MISP threat_level_id string (1=High, 2=Medium, 3=Low, 4=Undefined)."""
    blocked_at = (verdict_doc.get("blocked_at") or "").lower()
    if blocked_at == "layer1":
        return "1"  # High
    if blocked_at == "layer3":
        return "1"  # High
    if blocked_at in ("layer2", "layer2_tier1"):
        return "1"  # High
    # L2 Tier 2/3 or pipeline blended
    l2 = verdict_doc.get("l2") or {}
    engines = l2.get("engines") or {}
    structural = engines.get("structural") or {}
    red_flags = structural.get("red_flags") or structural.get("findings") or []
    if any("critical" in str(f) for f in red_flags):
        return "1"
    return "2"  # Medium


def _build_misp_event(verdict_doc: dict, settings) -> dict:
    """Build a MISP event payload containing only technical IoCs."""
    parsed = verdict_doc.get("parsed") or {}
    l1 = verdict_doc.get("l1") or {}
    l2 = verdict_doc.get("l2") or {}
    conf = float(verdict_doc.get("confidence") or 0.0)
    verdict = verdict_doc.get("verdict", "unknown")
    blocked_at = verdict_doc.get("blocked_at") or "pipeline"
    tlp = getattr(settings, "misp_default_tlp", "TLP:AMBER")

    attrs = []

    # Sender IP (ip-src)
    sender_ip = parsed.get("sender_ip") or ""
    if sender_ip:
        attrs.append({
            "type": "ip-src",
            "value": sender_ip,
            "category": "Network activity",
            "comment": "sender IP extracted from Received headers",
        })

    # Sending domain
    sender_domain = parsed.get("sender_domain") or ""
    if sender_domain:
        attrs.append({
            "type": "domain",
            "value": sender_domain,
            "category": "Network activity",
            "comment": "envelope sender domain",
        })

    # Extracted URLs (url attributes)
    urls: list[str] = parsed.get("urls") or []
    if not urls:
        # Fall back to L1 hits if available
        for hit in (l1.get("hits") or []):
            url = hit.get("url") or hit.get("value") or ""
            if url and url.startswith("http"):
                urls.append(url)
    for url in urls[:20]:  # cap at 20 to avoid oversized events
        attrs.append({
            "type": "url",
            "value": url,
            "category": "External analysis",
        })

    # Attachment SHA-256 hashes
    for sha in (parsed.get("attachment_hashes") or []):
        attrs.append({
            "type": "sha256",
            "value": sha,
            "category": "Payload delivery",
        })

    # Machine-generated verdict metadata (text attribute — no email content)
    meta_text = (
        f"PhishGuard verdict={verdict} confidence={conf:.2f} "
        f"blocked_at={blocked_at} "
        f"engine_scores={_engine_score_summary(l2)}"
    )
    attrs.append({
        "type": "text",
        "value": meta_text,
        "category": "Other",
        "comment": "auto-generated by PhishGuard — no email content",
    })

    # Build tag list
    tags = [
        {"name": "phishguard:auto-export"},
        {"name": tlp},
        {"name": "type:phishing" if verdict == "phishing" else "type:suspicious"},
    ]
    primary_intent = (
        (l2.get("engines") or {}).get("nlp") or {}
    ).get("primary_intent") or ""
    if primary_intent and primary_intent != "clean":
        tags.append({"name": f"phishguard:intent={primary_intent}"})

    return {
        "Event": {
            "info": f"PhishGuard auto-export — {verdict} [{blocked_at}] conf={conf:.2f}",
            "date": datetime.now(UTC).strftime("%Y-%m-%d"),
            "threat_level_id": _threat_level_id(verdict_doc),
            "analysis": "2",      # 2 = Ongoing analysis
            "distribution": "1",  # 1 = Organisation only (configurable upgrade later)
            "Tag": tags,
            "Attribute": attrs,
        }
    }


def _engine_score_summary(l2: dict) -> str:
    scores = l2.get("engine_scores") or {}
    return ",".join(f"{k}={v:.2f}" for k, v in scores.items() if isinstance(v, (int, float)))


async def _post_event(event: dict, misp_url: str, misp_key: str) -> dict | None:
    """POST the event to MISP and return the parsed response (or None on failure)."""
    try:
        import httpx
        hdrs = {
            "Authorization": misp_key,
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = misp_url.rstrip("/") + "/events"
        async with httpx.AsyncClient(verify=False, timeout=15) as client:
            resp = await client.post(url, json=event, headers=hdrs)
            resp.raise_for_status()
            return resp.json()
    except Exception as exc:
        raise RuntimeError(str(exc)) from exc


async def export_to_misp(verdict_doc: dict, settings) -> dict:
    """Export IoCs to MISP with retry. Returns a result dict for the pipeline document.

    Returns:
        {
            "exported": bool,
            "misp_event_id": str | None,
            "misp_event_uuid": str | None,
            "attribute_count": int,
            "export_status": "success" | "failed" | "not_applicable",
            "error": str | None,
        }
    """
    _not_applicable = {
        "exported": False,
        "misp_event_id": None,
        "misp_event_uuid": None,
        "attribute_count": 0,
        "export_status": "not_applicable",
        "error": None,
    }

    misp_url = getattr(settings, "misp_url", "") or ""
    misp_key = getattr(settings, "misp_api_key", "") or ""
    if not misp_url or not misp_key:
        return _not_applicable

    verdict = (verdict_doc.get("verdict") or "").lower()
    if verdict not in ("phishing", "suspicious"):
        return _not_applicable

    event_payload = _build_misp_event(verdict_doc, settings)
    attr_count = len(event_payload["Event"].get("Attribute", []))

    last_exc: str = ""
    for attempt in range(1, _MAX_RETRIES + 1):
        try:
            response = await _post_event(event_payload, misp_url, misp_key)
            ev = (response or {}).get("Event") or {}
            event_id = str(ev.get("id") or "")
            event_uuid = str(ev.get("uuid") or "")
            logger.info(
                "misp_exported",
                event_id=event_id,
                attr_count=attr_count,
                attempt=attempt,
            )
            return {
                "exported": True,
                "misp_event_id": event_id,
                "misp_event_uuid": event_uuid,
                "attribute_count": attr_count,
                "export_status": "success",
                "error": None,
            }
        except Exception as exc:
            last_exc = str(exc)
            logger.warning("misp_export_err", attempt=attempt, error=last_exc)
            if attempt < _MAX_RETRIES:
                await asyncio.sleep(_RETRY_BACKOFF_BASE ** attempt)

    logger.error("misp_export_failed", retries=_MAX_RETRIES, error=last_exc)
    return {
        "exported": False,
        "misp_event_id": None,
        "misp_event_uuid": None,
        "attribute_count": attr_count,
        "export_status": "failed",
        "error": last_exc,
    }
